[package]
name = "caretta-framework-example-migration"
version.workspace = true
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
sea-orm-migration.workspace = true
tokio.workspace = true
