[package]
name = "caretta-sync-example-core"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default=[]

[dependencies]
async-trait.workspace = true
caretta-sync.workspace = true
iroh.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1.17", features = ["net"] }
tonic.workspace = true
url.workspace = true
sea-orm-migration.workspace = true